name: Build iOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    env:
      XCODE_PROJECT: "JITEnabler.xcodeproj"
      XCODE_SCHEME: "JITEnabler"
      BUNDLE_ID: "com.jitenabler.app"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: List available Xcode versions
        run: |
          ls -la /Applications/ | grep Xcode
          xcodebuild -version
          
      - name: List available simulators
        run: |
          xcrun simctl list devices available
      
      - name: Make build script executable
        run: |
          chmod +x build-ios.sh
          
      - name: Build iOS app
        run: |
          echo "Building iOS app..."
          ./build-ios.sh
          
          # Verify the build
          ls -la build/ios/ipa/
      
      - name: Verify IPA file
        run: |
          echo "Verifying IPA file..."
          # Find the IPA file
          IPA_FILE=$(find build/ios/ipa -name "*.ipa" | head -1)
          
          if [ -z "$IPA_FILE" ]; then
            echo "Error: No IPA file found!"
            exit 1
          fi
          
          echo "Found IPA file: $IPA_FILE"
          ls -la "$IPA_FILE"
          
          # Verify the IPA file structure
          mkdir -p /tmp/ipa_check
          unzip -q "$IPA_FILE" -d /tmp/ipa_check
          ls -la /tmp/ipa_check
          
          # Check if Payload directory exists
          if [ ! -d "/tmp/ipa_check/Payload" ]; then
            echo "Error: Payload directory not found in IPA!"
            exit 1
          fi
          
          # Check if app exists in Payload
          APP_COUNT=$(find /tmp/ipa_check/Payload -name "*.app" -type d | wc -l)
          if [ "$APP_COUNT" -eq 0 ]; then
            echo "Error: No .app found in Payload directory!"
            exit 1
          fi
          
          echo "IPA file structure verified successfully!"
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-app-build
          path: build/ios/ipa/*.ipa
          if-no-files-found: error