name: Run Chat Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-chat-script:
    runs-on: ubuntu-latest

    steps:
    # Checks out the repository code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Specify your Python version (e.g., '3.8', '3.9', '3.10')

    # Install dependencies including openai
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai

    # Run the chat.py script with API key as environment variable
    - name: Run chat.py
      run: python chat.py
